### PR TITLE
Updated the CDN bootcss to cdnjs

### PR DESCRIPTION
**Pull request by shirooo39**
I think I've replaced every of the bootcss lines with cdnjs.  
the needed assets like the css and js are now pulled from cdnjs instead of bootcss.

screenshot

the assets now load faster compared to before.

I also have a question.

serving Jekyll from the master branch, I'm getting quite some error like missing packages.  
I ended up having to replace the content of the gem file (like adding those missing packages (thanks stackoverflow)) and now it serves fine.
will that affect anything?

and also, how do I build the theme like in the /build/ branch?

### CODE REVIEW

**Comment by KeJunMao** [comment]
master branch is source code
build branch is demo code, use gem https://rubygems.org/gems/jekyll-theme-mdui/

can you open a issues talk this?

**Comment by KeJunMao** [comment]
thx, this repo was wrote during i began to learn front-end, so the code is very  "%^&13&*2)(23", like my english

**Comment by shirooo39** [comment]
> thx, this repo was wrote during i began to learn front-end, so the code is very "%^&13&*2)(23", like my english

I've been looking into a static site generator that have good Material Design theme.
good thing I stumbled across MDUI and found this theme.

this theme was nicely done but it needs some adjustment like colored navbar and a dark theme if possible.
that Editor page is so powerful! people can easily create an article from there without having to go into a text editor and write markdown manually (even though I think we still need to write the content in markdown, but at least the experience is much better).

I tried VuePress, but I have no idea what I'm doing hahaha
I don't have strong knowledge in web programming, all I can do best is just code something simple in Python.

so having a really well-built theme like this is really nice.

I'm also glad that people can still get in touch with you, so we know that this repo isn't abandoned.

**Comment by KeJunMao** [comment]
> I've been looking into a static site generator that have good Material Design theme.

I'm very love MD toooo

> good thing I stumbled across MDUI and found this theme.

hahah, MDUI hasn't been updated for a long time

> this theme was nicely done but it needs some adjustment like colored navbar and a dark theme if possible.
that Editor page is so powerful! people can easily create an article from there without having to go into a text editor and write markdown manually (even though I think we still need to write the content in markdown, but at least the experience is much better).

this theme is old, the new time need to use Vue or React, not is JQ.

the Editor page is service static web site(like github page), and the [plugin](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins) :( ,if you have host ,you can choose something else

> I don't have strong knowledge in web programming, all I can do best is just code something simple in Python.

hahahah, front-end is easy! i think

> so having a really well-built theme like this is really nice.
I'm also glad that people can still get in touch with you, so we know that this repo isn't abandoned.

thx again

**Pull request merged**
